# Generated by Django 4.2.2 on 2023-07-19 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='url',
            field=models.CharField(default='None', max_length=100),
            preserve_default=False,
        ),
    ]
